services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Application\:
    resource: '../../src/Application/*'
    exclude: '../../src/Application/*/Command/*'
    tags:
      - { name: tactician.handler, typehints: true }

  App\:
    resource: '../../src/*'
    exclude: '../../src/{*/*/Mock,Repository,Domain,Application,Entity,Migrations,Tests}'


  App\Controller\:
    resource: '../../src/Controller/'
    tags: ['controller.service_arguments']
